# Generated by Django 4.2 on 2025-04-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_emb'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
