# Generated by Django 4.2 on 2025-04-07 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_movie_year2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='year2',
        ),
    ]
